language: ruby
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.8
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - jruby-head

install:
  - gem install bundler -v 1.17.3
  - bundle install --jobs=3 --retry=3
